version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    #links:
    depends_on:
      - mongodb
# networks:
#   dev:
#     name: mongo_network
#     driver: bridge
